### ISSUE TITLE
ASCII Wettericons

### ISSUE THREAD

**Issue by kaspar-allenbach** [gexclaude/homebrew-tap#1]
Glaub das funktioniert nicht: https://codepen.io/Sepp/pen/RMbNKK

**Comment by kaspar-allenbach** [comment]
Ds VNA chönt me z.b. so mache chli Platzsparend:

```
+--------------------------------------------------------------+
| Ds wätter      | Morge: 0° / 4mm / 30%   | Sunne             |
| hüt düre Tag   | Nami:  0° / 4mm / 30%   | Räge              |
|                | Abe:   0° / 4mm / 30%   | Gwitter           |
+--------------------------------------------------------------+
| x° = Temp. / Ymm = Rägemängi / Z% = Rägewahrschindlechkeit   | 
+--------------------------------------------------------------+
```

**Comment by kaspar-allenbach** [comment]
Gäu me cha im terminal d zeiche o farbig mache?

**Comment by kaspar-allenbach** [comment]
So müestme eifach no uf die 15 symbol ds Bärndütsche wätter mappe. vilech machemer das grad ider API

**Comment by gexclaude** [comment]
Hauptrepo ist hier: https://github.com/gexclaude/aaregurucli (homebrew-tap ist nur für die homebrew sache unter Mac)

**Comment by gexclaude** [comment]
ja i gloube ou, dass ds asciiart ds viu platz brucht, damits o cool würd usgseh.
ds VNA chöimer guet mau i däm stil mache - wie ging, chli starte u de chame ging no verbessere.

ds mapping vode symbol uf bärndütsch wär natürläch cool das grad im API ds mache.

ja, me cha farbe nutze. ir momentante version machi das ou, funktioniert aber nur mit entsprechende terminals wie tty. bspw. unger win7 mit dos prompt geit das nid.
